[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
bincode = "2.0.1"
sled = "0.34.7"
bs58 = "0.5.1"
data-encoding = "2.9.0"
rust-crypto = "0.2.36"
ring = "0.17.14"
once_cell = "1.21.3"

[dev-dependencies]
tempfile = "3.10.1"
